# Generated by experiments/bt_league/candidate.py.
SPEC = {'dsl_version': '3.0',
 'candidate_id': 'ev_g003_a01',
 'parent_id': 'open_policy_v003',
 'summary': 'Reduced LAUNCH_COOLDOWN_S from 30s to 20s to permit quicker follow-up shots, and '
            'slightly increased HOT_RANGE_M to 165000 for earlier engagement. Maintained '
            'zero-violation performance.',
 'policy_source': '<compiled into policy.py>',
 'policy_sha256': 'bcd86fe13a4cb23108b43a7a181f03df7d7e6f7abd43abb326503ed4786a55da'}
