# Generated by experiments/bt_league/candidate.py.
SPEC = {'dsl_version': '3.0',
 'candidate_id': 'ev_g001_a03',
 'parent_id': 'open_policy_v001',
 'summary': 'Increased launch ranges, heading error tolerances, and crank duration to boost '
            'engagement and hit probability.',
 'policy_source': '<compiled into policy.py>',
 'policy_sha256': '09372d44ff5d714a6bb00550d423fbc2f291e45e00cbff7867e7654d19dcc32f'}
